[project]
name = "northwind-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "pandas>=2.2.3",
    "psycopg>=3.2.5",
    "psycopg-binary>=3.2.5",
    "sqlalchemy>=2.0.38",
]
